### ISSUE TITLE
88SR版実機動作

### ISSUE THREAD

**Issue by toyoshim** [tablacus/LSX-Dodgers#12]
PC-8801FEにて動作確認を行ったのですが、起動はするもののディスクアクセスが不安定のようです。

V2/4MHzで起動した場合:
```
A>dir
Error!
A>
```

V2/8MHzで起動した場合:
```
A>dir
（しばらく待った後に）
$0028$0028$0028...（以下、無限に同じメッセージが流れていく）
```

となりました。

M88でもpseudoではなく実機ROMを使うとError!になるようです（周波数設定に関わらず常にError!の方のパタン）

**Comment by tablacus** [comment]
LSX-Dodgers v1.48アップしました。
v1.47PR2、PR3でいくつかの修正を行ってみました。
また、時間があるときに試していただけると幸いです。

https://github.com/tablacus/LSX-Dodgers/releases/

**Comment by toyoshim** [comment]
ありがとうございます、実機で動作しましたので、本報告はcloseさせて頂きます！
