### ISSUE TITLE
ZASM.COM/ZASM.EXEで再構築できるソースコード

### ISSUE THREAD

**Issue by Zephyr1969** [tablacus/LSX-Dodgers#3]
このDOS素晴らしいのですが、更新する環境構築が難しいと思っています。
それで、ZASM.COM/ZASM.EXEで再構築できるようにソースコードを修正したのですが、
こちらのサイトで公開していただければ幸甚です。

**Comment by tablacus** [comment]
ありがとうございます。プルリク送ってください。

**Comment by Zephyr1969** [comment]
お恥ずかしい話、プルリクエストでソースコードを載せる方法がよくわかりません。orz

**Comment by tablacus** [comment]
では、このIssueに以下の様にアップしていただけますでしょうか？
[LSX-Dodgers.zip](https://github.com/tablacus/LSX-Dodgers/files/6912056/LSX-Dodgers.zip)

1. ソースファイルをZIPで圧縮
2. Issueの文字入力エリアに上記のZIPファイルをドラッグ＆ドロップ

すみませんが、よろしくお願いします。

※余談ですが、GitHubのIssueはペイントなどで画像をコピーして、Issueで文字入力中に貼り付けるとそのままペーストされて便利です。

**Comment by Zephyr1969** [comment]
[lsx.zip](https://github.com/tablacus/LSX-Dodgers/files/6912270/lsx.zip)
これでよいのでしょうか。
念のため、prnファイルも入れてあります。よろしくお願いします。

**Comment by tablacus** [comment]
受け取りました。フォルダ zasm を作成してそこで公開します。
使用したZASMのバージョンとダウンロードできるサイトを教えていただけると幸いです。

**Comment by Zephyr1969** [comment]
ZASMのバージョンは、Vectorの下記から手に入る1.64です。
https://www.vector.co.jp/soft/dos/prog/se010314.html

**Comment by tablacus** [comment]
ありがとうございます。readmeに追記しておきます。
