### ISSUE TITLE
LD起動時にグラフィック画面が表示される

### ISSUE THREAD

**Issue by SuperTurboZ** [tablacus/LSX-Dodgers#8]
Ver.1.43のd88をFDに書き戻してX1turboZでFDから起動したところ、パレットが初期化されてグラフィックGRAMが表示された状態になりました。

エミュレータではメモリが全て0x00の状態で起動するので気が付きませんでしたが、BASICでpaint(0,0),&h74実行後にldをipl起動してみたところ同様に画面に表示されました。

![2022-10-07_20-22-09](https://user-images.githubusercontent.com/42510238/194541602-70d174b5-8f8b-486b-a7ad-bc7dc2c6229d.png)

**Comment by tablacus** [comment]
パレットの初期化処理は省略するようにします。

**Comment by tablacus** [comment]
LSX-Dodgers 1.45でパレット初期化処理を削除しました。
